
admin_score_home:
    path:     /admin
    defaults: { _controller: VideoAdminBundle:Home:tablesTab }

admin_score_tables_tab:
    path:     /admin/tables
    defaults: { _controller: VideoAdminBundle:Home:tablesTab }

admin_score_classes_tab:
    path:     /admin/classes
    defaults: { _controller: VideoAdminBundle:Home:classesTab }

admin_score_images_tab:
    path:     /admin/images
    defaults: { _controller: VideoAdminBundle:Home:imagesTab }

admin_score_video_tab:
    path:     /admin/video
    defaults: { _controller: VideoAdminBundle:Home:videoTab }

admin_score_mail_tab:
    path:     /admin/mail
    defaults: { _controller: VideoAdminBundle:Home:mailTab }

admin_score_claims_tab:
    path:     /admin/claims
    defaults: { _controller: VideoAdminBundle:Home:claimsTab }

