parameters:
#    sportsrush_users.example.class: SportsRush\UsersBundle\Example

services:

#    sportsrush_users.example:
#        class: %sportsrush_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
